# Sobe o Kafka (modo KRaft, sem Zookeeper) + Kafka UI + Aplicação Spring
# Uso padrão: docker compose up -d (Sobe apenas Kafka e Kafka UI)
# Uso completo: docker compose --profile app up -d --build (Sobe tudo, incluindo o app)
services:
  kafka:
    image: apache/kafka:3.8.0
    container_name: kafka
    ports:
      - "9092:9092" # acesso a partir da sua máquina (apps Spring)
    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      # INTERNAL = outros containers | EXTERNAL = sua máquina | CONTROLLER = KRaft
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      # Com 1 broker só, fator de replicação precisa ser 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 > /dev/null 2>&1"]
      interval: 10s
      timeout: 10s
      retries: 10

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8090:8080" # abra http://localhost:8090
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      kafka:
        condition: service_healthy

  # --- O QUE MUDOU: ADIÇÃO DO SEU MICROSERVIÇO ---
  hello-kafka:
    profiles: ["app"]
    build: ./hello-kafka     # Altere para o caminho relativo correto da pasta do seu app se necessário
    container_name: hello-kafka
    ports:
      - "8080:8080"          # Expõe a porta do Spring para sua máquina física
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092 # Sobrescreve o localhost do seu application.yml dentro do Docker
    depends_on:
      kafka:
        condition: service_healthy # Garante que o Spring só tente iniciar quando o Kafka estiver 100% pronto
